# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
services:
  app:
    build:
      context: .
    image: portfolio-app
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: package.json
          action: rebuild
